library(dplyr)
library(patchwork)
library(VGAM)
library(gplots)
library(ggplot2)
library(pracma)
library(resample)
library(foreach)
library(distances)
library(utils)
library(doParallel)
library(scDEED)
library(SeuratDisk)
library(hdf5r)
library(Seurat)
library(gridExtra)
library(dplyr)
library(patchwork)
library(VGAM)
library(gplots)
library(ggplot2)
library(pracma)
library(resample)
library(foreach)
library(distances)
library(utils)
library(doParallel)
library(scDEED)
Convert("854_Epcam_cells.h5ad", dest = "h5seurat", overwrite = FALSE)
data <- LoadH5Seurat("854_Epcam_cells.h5seurat")
data = NormalizeData(data)
data = ScaleData(data)
data = FindVariableFeatures(data)
counts <- GetAssayData(data, slot = "counts")
data[["RNA"]] <- CreateAssayObject(counts = counts)
DefaultAssay(data) <- "RNA"
data = NormalizeData(data)
data = ScaleData(data)
data = FindVariableFeatures(data)
data = ScaleData(data)
data = FindVariableFeatures(data)
data = RunPCA(data)
Seurat::ElbowPlot(data)

K = 5
start = Sys.time()
end = Sys.time()
time_elapse = data.frame(start = start, end = end, type = 'umap')
result_umap = scDEED(data, K = K, reduction.method = 'umap',  n_neighbors = c(5, 10, 20, 30, 40,50), min.dist = c(0.1, 0.4))
time_elapse = bind_rows(time_elapse, data.frame(start = start, end = end, type = 'umap'))
best_perplexity = which(result_umap$`number of dubious cells`==min(result_umap$`number of dubious cells`))
saveRDS(result_umap, '854_umap_pc5.Rds')
saveRDS(time_elapse, '854_umap_pc5_time.Rds')
head(result_umap$num_dubious)
result_umap$num_dubious
K = 15
start = Sys.time()
end = Sys.time()
time_elapse = data.frame(start = start, end = end, type = 'umap')
result_umap = scDEED(data, K = K, reduction.method = 'umap',  n_neighbors = c(5, 10, 20, 30, 40,50), min.dist = c(0.1, 0.4))
time_elapse = bind_rows(time_elapse, data.frame(start = start, end = end, type = 'umap'))
best_perplexity = which(result_umap$`number of dubious cells`==min(result_umap$`number of dubious cells`))
saveRDS(result_umap, '854_umap_pc15.Rds')
saveRDS(time_elapse, '854_umap_pc15_time.Rds')
result_umap$num_dubious
K = 20
start = Sys.time()
end = Sys.time()
time_elapse = data.frame(start = start, end = end, type = 'umap')
result_umap = scDEED(data, K = K, reduction.method = 'umap',  n_neighbors = c(5, 10, 20, 30, 40,50), min.dist = c(0.1, 0.4))
time_elapse = bind_rows(time_elapse, data.frame(start = start, end = end, type = 'umap'))
best_perplexity = which(result_umap$`number of dubious cells`==min(result_umap$`number of dubious cells`))
saveRDS(result_umap, '854_umap_pc20.Rds')
saveRDS(time_elapse, '854_umap_pc20_time.Rds')
result_umap$num_dubious
K = 30
start = Sys.time()
end = Sys.time()
time_elapse = data.frame(start = start, end = end, type = 'umap')
result_umap = scDEED(data, K = K, reduction.method = 'umap',  n_neighbors = c(5, 10, 20, 30, 40,50), min.dist = c(0.1, 0.4))
time_elapse = bind_rows(time_elapse, data.frame(start = start, end = end, type = 'umap'))
best_perplexity = which(result_umap$`number of dubious cells`==min(result_umap$`number of dubious cells`))
saveRDS(result_umap, '854_umap_pc30.Rds')
saveRDS(time_elapse, '854_umap_pc30_time.Rds')
result_umap$num_dubious
K = 35
start = Sys.time()
end = Sys.time()
time_elapse = data.frame(start = start, end = end, type = 'umap')
result_umap = scDEED(data, K = K, reduction.method = 'umap',  n_neighbors = c(5, 10, 20, 30, 40,50), min.dist = c(0.1, 0.4))
time_elapse = bind_rows(time_elapse, data.frame(start = start, end = end, type = 'umap'))
best_perplexity = which(result_umap$`number of dubious cells`==min(result_umap$`number of dubious cells`))
saveRDS(result_umap, '854_umap_pc35.Rds')
saveRDS(time_elapse, '854_umap_pc35_time.Rds')
result_umap$num_dubious
savehistory("~/R_clustering/r_854.Rhistory")
