library(devtools)
library(gridExtra)
library(dplyr)
library(patchwork)
library(VGAM)
library(gplots)
library(ggplot2)
library(pracma)
library(resample)
library(foreach)
library(distances)
library(utils)
library(doParallel)
library(scDEED)
library(Seurat)
library(SeuratDisk)
Convert("dataset_1_clean.h5ad", dest = "h5seurat", overwrite = FALSE)
pbmc_raw <- LoadH5Seurat("dataset_1_clean.h5seurat")
pbmc_raw
counts <- GetAssayData(data, slot = "counts")
data[["RNA"]] <- CreateAssayObject(counts = counts)
DefaultAssay(data) <- "RNA"
data = NormalizeData(data)
data = ScaleData(data)
data = FindVariableFeatures(data)
data = ScaleData(data)
data = FindVariableFeatures(data)
data = RunPCA(data)
K = 30
start = Sys.time()
end = Sys.time()
time_elapse = data.frame(start = start, end = end, type = 'umap')
result_umap = scDEED(data, K = K, reduction.method = 'umap',  n_neighbors = c(5, 10, 20, 30, 40,50), min.dist = c(0.1, 0.2, 0.4))
time_elapse = bind_rows(time_elapse, data.frame(start = start, end = end, type = 'umap'))
best_perplexity = which(result_umap$`number of dubious cells`==min(result_umap$`number of dubious cells`))
saveRDS(result_umap, 'dataset_1_clean_pc30.Rds')
saveRDS(time_elapse, 'dataset_1_clean_pc30_time.Rds')
result_umap$num_dubious
K = 20
start = Sys.time()
end = Sys.time()
time_elapse = data.frame(start = start, end = end, type = 'umap')
result_umap = scDEED(data, K = K, reduction.method = 'umap',  n_neighbors = c(5, 10, 20, 30, 40,50), min.dist = c(0.1, 0.2, 0.4))
time_elapse = bind_rows(time_elapse, data.frame(start = start, end = end, type = 'umap'))
best_perplexity = which(result_umap$`number of dubious cells`==min(result_umap$`number of dubious cells`))
saveRDS(result_umap, 'dataset_1_clean_pc20.Rds')
saveRDS(time_elapse, 'dataset_1_clean_pc20_time.Rds')
result_umap$num_dubious
K = 15
start = Sys.time()
end = Sys.time()
time_elapse = data.frame(start = start, end = end, type = 'umap')
result_umap = scDEED(data, K = K, reduction.method = 'umap',  n_neighbors = c(5, 10, 20, 30, 40,50), min.dist = c(0.1, 0.2, 0.4))
time_elapse = bind_rows(time_elapse, data.frame(start = start, end = end, type = 'umap'))
best_perplexity = which(result_umap$`number of dubious cells`==min(result_umap$`number of dubious cells`))
saveRDS(result_umap, 'dataset_1_clean_pc15.Rds')
saveRDS(time_elapse, 'dataset_1_clean_pc15_time.Rds')
result_umap$num_dubious
